version: '3.7'

services:
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - nifi-conf:/opt/nifi/nifi-current/conf
    environment:
      NIFI_WEB_HTTP_PORT: 8080
      NIFI_WEB_PROXY_HOST: localhost:8080
      SINGLE_USER_CREDENTIALS_USERNAME: admin
      SINGLE_USER_CREDENTIALS_PASSWORD: 111111111111

volumes:
  nifi-conf: